### PR TITLE
Added property compare option, for dealing with other element being...

### PR DESCRIPTION
**Pull request by DanilloCorvalan**
Added property compare option, for dealing with other element being filtered.

### CODE REVIEW

**Comment by cheeaun** [comment]
What is the file **elementCompareProperty_Sample.html** for?

**Comment by DanilloCorvalan** [comment]
It's a sample html using the new option

**Comment by cheeaun** [comment]
Ah okay. Sorry this code is quite old and outdated, my bad. I get your use case but I think a much better solution would be passing a custom `filter` function/selector. Perhaps shouldn't have extended jQuery to have the `:inContains()` selector too.

**Comment by cheeaun** [comment]
@DanilloCorvalan I've added a custom `filter` function here 91551e276d0a9e0b3081adff3aafa7e5c374afce where you'll have more control on how the filtering works. I'm closing this pull request now, but feel free to submit another pull request if this doesn't fix your use case. Thanks.

**Comment by DanilloCorvalan** [comment]
Many thanks! I'll get this version and do some tests

On Sun, Mar 31, 2013 at 6:57 AM, Lim Chee Aun notifications@github.comwrote:

> @DanilloCorvalan https://github.com/DanilloCorvalan I've added a custom
> filter function here 91551e2https://github.com/cheeaun/jquery.livefilter/commit/91551e276d0a9e0b3081adff3aafa7e5c374afcewhere you'll have more control on how the filtering works. I'm closing this
> pull request now, but feel free to submit another pull request if this
> doesn't fix your use case. Thanks.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/cheeaun/jquery.livefilter/pull/3#issuecomment-15689294
> .

## 

Obrigado,
Danillo Corvalan de Barros

**Pull request closed without merging**
